name: Convert PNG to TGA (Medium and Small)

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up ImageMagick
      run: sudo apt-get update && sudo apt-get install -y imagemagick

    - name: Convert PNGs to TGA (to chaos/gfx/flags/medium and small)
      run: |
        find chaos/gfx/flags -type f -name "*.png" ! -path "*/medium/*" ! -path "*/small/*" | while read file; do
          base=$(basename "$file" .png)
          mkdir -p chaos/gfx/flags/medium chaos/gfx/flags/small
          convert "$file" -resize 41x26 -define tga:bits=32 "TGA:chaos/gfx/flags/medium/${base}.tga"
          convert "$file" -resize 10x7  -define tga:bits=32 "TGA:chaos/gfx/flags/small/${base}.tga"
        done

    - name: Debug - List TGA files
      run: |
        echo "Medium:"
        find chaos/gfx/flags/medium -name "*.tga"
        echo "Small:"
        find chaos/gfx/flags/small -name "*.tga"

    - name: Commit and push TGA files
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        if git status --porcelain | grep .; then
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add chaos/gfx/flags/medium/*.tga chaos/gfx/flags/small/*.tga
          git commit -m "Add resized TGA files to medium and small folders"
          git push origin main
        else
          echo "No changes to commit."
        fi
