name: Combine Textures for Resourcepack

on:
  workflow_dispatch:
  push:
    paths:
      - 'parts/*.png'
      - '.github/workflows/E.yml'
      - 'A.py'

jobs:
  combine:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Pillow
      run: pip install Pillow numpy tqdm skimage

    - name: Generate combined textures
      run: python B.py

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Stash uncommitted changes before pull
      run: |
        git add .
        git stash --include-untracked

    - name: Pull latest changes
      run: |
        git fetch origin
        git checkout $(git rev-parse --abbrev-ref HEAD)
        git pull --rebase origin $(git rev-parse --abbrev-ref HEAD)

    - name: Reapply stashed changes
      run: git stash pop || true

    - name: Commit and push generated textures
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto: Generate combined textures for resourcepack"
        file_pattern: "chaos/map/*.png"
